# Generated by Django 5.1.6 on 2025-03-10 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='tender',
        ),
        migrations.RemoveField(
            model_name='evaluationresponse',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='biddocument',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='signed_by',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tender',
        ),
        migrations.RemoveField(
            model_name='evaluationcriterion',
            name='tender',
        ),
        migrations.RemoveField(
            model_name='evaluationresponse',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='evaluationresponse',
            name='evaluated_by',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Industry Category', 'verbose_name_plural': 'Industy Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name': 'Industry Sub Category', 'verbose_name_plural': 'Industy Sub -Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='tenderdocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tender',
            name='SubCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenders.subcategory'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='description',
            field=models.TextField(verbose_name='Tender summary'),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='BidDocument',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='EvaluationCriterion',
        ),
        migrations.DeleteModel(
            name='EvaluationResponse',
        ),
        migrations.RemoveField(
            model_name='tenderdocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='tenderdocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='tenderdocument',
            name='version',
        ),
    ]
