# Generated by Django 5.1.6 on 2025-03-10 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_alter_bid_unique_together_remove_bid_bidder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications for new matching tenders')),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='immediate', max_length=20)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenderSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords to match in tender title and description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Subscribe to all tenders in this category', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.category')),
                ('procurement_process', models.ForeignKey(blank=True, help_text='Subscribe to all tenders with this procurement process', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.procurementprocess')),
                ('subcategory', models.ForeignKey(blank=True, help_text='Subscribe to all tenders in this subcategory', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('delivery_status', models.CharField(blank=True, help_text='Email delivery status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenders.tender')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenders.tendersubscription')),
            ],
        ),
        migrations.AddIndex(
            model_name='tendersubscription',
            index=models.Index(fields=['user', 'is_active'], name='tenders_ten_user_id_95b350_idx'),
        ),
        migrations.AddIndex(
            model_name='tendersubscription',
            index=models.Index(fields=['category'], name='tenders_ten_categor_6c25ae_idx'),
        ),
        migrations.AddIndex(
            model_name='tendersubscription',
            index=models.Index(fields=['subcategory'], name='tenders_ten_subcate_1e40a3_idx'),
        ),
        migrations.AddIndex(
            model_name='tendersubscription',
            index=models.Index(fields=['procurement_process'], name='tenders_ten_procure_ea5357_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tendersubscription',
            unique_together={('user', 'category', 'subcategory', 'procurement_process')},
        ),
        migrations.AddIndex(
            model_name='tendernotification',
            index=models.Index(fields=['is_sent'], name='tenders_ten_is_sent_ccd32a_idx'),
        ),
        migrations.AddIndex(
            model_name='tendernotification',
            index=models.Index(fields=['sent_at'], name='tenders_ten_sent_at_eb97cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tendernotification',
            unique_together={('subscription', 'tender')},
        ),
    ]
