# Generated by Django 5.1.6 on 2025-03-10 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_notificationpreference_tendersubscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('published', 'Published'), ('evaluation', 'Under Evaluation'), ('awarded', 'Awarded'), ('closed', 'Closed'), ('canceled', 'Canceled')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Industry Category', 'verbose_name_plural': 'Industry Categories'},
        ),
        migrations.AlterModelOptions(
            name='procurementprocess',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name': 'Industry Sub Category', 'verbose_name_plural': 'Industry Sub Categories'},
        ),
        migrations.RenameField(
            model_name='tender',
            old_name='SubCategory',
            new_name='subcategory',
        ),
        migrations.AddField(
            model_name='procurementprocess',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='tendersubscription',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['slug'], name='tenders_ten_slug_798e67_idx'),
        ),
        migrations.AddIndex(
            model_name='tendersubscription',
            index=models.Index(fields=['slug'], name='tenders_ten_slug_750636_idx'),
        ),
        migrations.AddField(
            model_name='tenderstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenderstatushistory',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tenders.tender'),
        ),
    ]
