# Generated by Django 5.1.6 on 2025-07-24 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('status_change', 'Status Change'), ('document_upload', 'Document Upload')], max_length=20)),
                ('details', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenders.tender')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validity_days', models.PositiveIntegerField(default=90)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('qualified', 'Technically Qualified'), ('disqualified', 'Disqualified'), ('awarded', 'Awarded'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bids', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_bids', to='accounts.company')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tenders.tender')),
            ],
            options={
                'ordering': ['-submission_date'],
                'unique_together': {('tender', 'bidder')},
            },
        ),
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='bid_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bids.bid')),
                ('required_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_documents', to='tenders.tenderrequireddocument')),
            ],
            options={
                'unique_together': {('bid', 'required_document')},
            },
        ),
    ]
